spring:
  application:
    name: GeometricEfficiencyTool
  data:
    mongodb:
      uri: mongodb://root:example@localhost:27017/geometricEfficiency?authSource=admin

      gridfs:
        default-timezone: America/Sao_Paulo
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
springdoc:
  swagger-ui:
    path: /swagger-ui
user:
  timezone: America/Sao_Paulo

api:
  security:
    config:
      secret: ${JWT_SECRET:my-secret-key}

server:
  port: 8080
  error:
    include-stacktrace: never

app:
  base:
    url: ${FRONT_URL:http://localhost:4200}