spring.application.name=GeometricEfficiencyTool
springdoc.swagger-ui.path=/swagger-ui
spring.data.mongodb.uri=mongodb://root:example@localhost:27017/geometricEfficiency?authSource=admin
spring.data.mongodb.gridfs.default-timezone=America/Sao_Paulo
user.timezone=America/Sao_Paulo